feat: OTC desk
galacticcouncil/warehouse pull request #165
Opened 2023-02-11 21:30 UTC by vgantchev

Related PR:
https://github.com/galacticcouncil/HydraDX-node/pull/515

This PR introduces a pallet which enables over-the-counter trading.

2023-02-13 08:59 UTC, enthusiastmartin reviewed
Reviewed the main implementation only - i haven't looked at tests or benchmarking yet. 

And only focused mostly from the rust and code quality perspective - i will do logic in another review round once my comments are resolved;-)

2023-02-13 08:59 UTC, enthusiastmartin commented on Cargo.toml
> +	"otc"
```suggestion
	"otc",
```

2023-02-13 08:59 UTC, enthusiastmartin commented on liquidity-mining/Cargo.toml
> -registry-traits = { package="hydradx-traits", git = "https://github.com/galacticcouncil/warehouse", rev="fcebd285141ce9ed15136f6102fa6396605d96af", default-features = false }
why this is resolved in the PR

2023-02-13 08:59 UTC, enthusiastmartin commented on liquidity-mining/src/lib.rs
> +use hydradx_traits::{pools::DustRemovalAccountWhitelist, registry::Registry};
why any changes in lm in this PR

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/README.md
> +TODO
todo

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/Cargo.toml
> +pallet-currencies = { path = "../currencies", default-features = false }
it seems that tsome of the depedencies are not needed in the actual implemeantion:

- balances
- math
- traits
- currencies

maybe others ?

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +            + NamedMultiReservableCurrency<Self::AccountId, ReserveIdentifier = NamedReserveIdentifier>;
you should not need Extended in the pallet implementation.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +            asset_sell: T::AssetId,
i'd consider to use in and out instead of sell and buy, so it is consistent with naming across our pallets.

of course, if that would make sense.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +            Self::validate_place_order(order.clone(), amount_sell)?;
change the validate_place_order to take the order by reference, so there wont be a need to clone it. 

it will make much more sense, since you need to continue using the same order

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +            Self::deposit_event(Event::OrderPlaced {
Switch the order of insert and deposit event, so no need to clone it.

Or use the parameters instead of values from the order object. The order has not changed , that means the input parameters should be correct.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +            amount_fill: Balance,
i'd use asset and amount instead of asset_fill, amount_fill - the name of the function is clear enough to understand what asset and amount refers to.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +            <Orders<T>>::try_mutate_exists(order_id, |maybe_order| -> DispatchResult {
it should be enough to use try_mutate. The storage if OptionQuery so it should return an option regardless.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +                let amount_receive = Self::amount_receive(order, amount_sell, amount_fill)?;
The names of functions `amount_sell` and `amount_receive` are not very clear what they really do here. 

they are the same as the variables, so i am wondering what they supposed to do. I havent yet checked their implemeantion but from just the code reading, it would be nice to understand what they are for.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +                Self::validate_fill_order(order, who.clone(), asset_fill, amount_sell, amount_fill, amount_receive)?;
Same as before - if it takes is be reference, no need for clone.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +                Self::execute_deal(order_id, order, who.clone(), amount_fill, amount_receive)?;
Probably here it would be also good to take the account (who) be reference.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +                let remaining_amount_buy = Self::amount_remaining(order.amount_buy, amount_fill)?;
same comment as for amouint_sell and amount_fill .

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +                    Self::update_storage(order, amount_fill)?;
i am not really a fan of this approach.  becayuse the storage is not really updated as part of the "update_storage" function. 

consider doing something like this:
1. change update_storage to update_order
2. take the order by value
3. within the update_order, update the order 
4. return it back and assign it to maybe_order.

this way, it consumes the order, which is fine, because you no longer need it. and you get back new order. but there wont any moving needed.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +        ensure!(order.amount_buy >= min_amount_buy, Error::<T>::OrderSizeTooSmall);
at first sight, these two lines feel that they do exactlly the same. 

i'd suggest to either:

combine the min buy and ED check into one function call "ensure_min_order_size". 

or

rename it to ensure_ed 

i'd prefer the first.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +        ensure!(amount_sell >= min_amount_sell, Error::<T>::OrderSizeTooSmall);
same applies for this one too.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +        order: &mut Order<T::AccountId, T::AssetId>,
why mutable is required here ?  i cant figure it out.

regardless, if the order needs to be mutable - the naming of the function is not correct because the naming suggests that it only validates it, but mutable indicates that something is changing too.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +                );
as before - ifi you combine this into one - it will be more clear.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +        let prefix = b"otc";
make this as constant somewhere.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +    fn amount_sell(order_id: OrderId, order: &mut Order<T::AccountId, T::AssetId>) -> Balance {
again - all these function use mutable referecne - it does not seem it is needed.

2023-02-13 08:59 UTC, enthusiastmartin commented on otc/src/lib.rs
> +        order: &mut Order<T::AccountId, T::AssetId>,
mut?

2023-02-13 11:32 UTC, apopiak commented on otc/src/lib.rs
> +            Self::deposit_event(Event::OrderPlaced {
insert should be possible with a `&order`, too

2023-02-13 11:32 UTC, apopiak commented on otc/src/lib.rs
> +        hashed_array
what's the benefit of hashing here?

2023-02-13 12:08 UTC, vgantchev commented on liquidity-mining/Cargo.toml
> -registry-traits = { package="hydradx-traits", git = "https://github.com/galacticcouncil/warehouse", rev="fcebd285141ce9ed15136f6102fa6396605d96af", default-features = false }
because impl in hydradx-node depended on another PR which was not merged until this morning

2023-02-13 18:46 UTC, vgantchev commented on otc/Cargo.toml
> +pallet-currencies = { path = "../currencies", default-features = false }
removed  balances, math and currencies - can use orml_tokens indeed

traits is used for `Registry`

2023-02-13 18:51 UTC, vgantchev commented on otc/src/lib.rs
> +            asset_sell: T::AssetId,
I was thinking about it but _in and _out don't make much sense outside the context of pools imo :)

2023-02-13 18:55 UTC, vgantchev commented on otc/src/lib.rs
> +            <Orders<T>>::try_mutate_exists(order_id, |maybe_order| -> DispatchResult {
it's by design: try_mutate_exists allows to clean storage if order is fill by setting it to `None`

https://crates.parity.io/frame_support/storage/trait.StorageMap.html#tymethod.try_mutate_exists

2023-02-13 20:44 UTC, vgantchev commented on otc/src/lib.rs
> +                    Self::update_storage(order, amount_fill)?;
good suggestion

2023-02-14 08:25 UTC, enthusiastmartin commented on otc/Cargo.toml
> +pallet-currencies = { path = "../currencies", default-features = false }
why need of orml-tokens - it should be generic enough so it does not depend on concrete implemenation. 

if used only in tests - then it should be in dev dependencies.

2023-02-14 08:26 UTC, enthusiastmartin commented on otc/src/lib.rs
> +            asset_sell: T::AssetId,
yes , kind of agree. but you can also see the in and out as in the protocol, out of the protocol.  Or into the account, out of the account.

2023-02-14 08:27 UTC, enthusiastmartin commented on otc/src/lib.rs
> +            <Orders<T>>::try_mutate_exists(order_id, |maybe_order| -> DispatchResult {
fair enough

2023-02-17 13:22 UTC, vgantchev commented on otc/Cargo.toml
> +pallet-currencies = { path = "../currencies", default-features = false }
this is where it is indeed

2023-02-17 13:26 UTC, vgantchev commented on otc/src/lib.rs
> +            asset_sell: T::AssetId,
oki

2023-02-23 13:17 UTC, enthusiastmartin submitted a review, later dismissed
one important issue about the possible multiplication overflow. 

I'd suggest to consider creating some property tests

2023-02-23 13:17 UTC, enthusiastmartin commented on otc/src/lib.rs
> +        NoPermission,
Forbidden ?

2023-02-23 13:17 UTC, enthusiastmartin commented on otc/src/lib.rs
> +        if !order.partially_fillable {
nitpick: personally, i would check the true first.  meaing `if order.partiall_fillable`.

2023-02-23 13:17 UTC, enthusiastmartin commented on otc/src/lib.rs
> +                let remaining_amount_in = Self::calculate_difference(order.amount_in, amount)?;
you actually calculate the remaining amount twice. first time in validate_fill_order and the second time here. 

i wonder if it could be refactored in some cleaner way.

2023-02-23 13:17 UTC, enthusiastmartin commented on otc/src/lib.rs
> +            .ok_or(Error::<T>::MathError)
i believe this multiplication can easily overflow if only u128 is used.

2023-02-24 19:38 UTC, mrq1911 requested changes

2023-02-24 19:38 UTC, mrq1911 commented on otc/src/lib.rs
> +        ensure!(order.asset_in == asset, Error::<T>::AssetNotInOrder);
this doesn't have to be checked when you don't allow user to set it ;)

2023-02-24 19:38 UTC, mrq1911 commented on otc/src/lib.rs
> +        InsufficientBalance,
this error is redundant as it will be checked and thrown by currencies pallet, therefore there is no need for this error in this pallet at all

2023-02-24 19:38 UTC, mrq1911 commented on otc/src/lib.rs
> +        pub fn fill_order(
i would consider splitting it into two functions, one for fully filling the order and the second for partially fill as naively i would assume that fully filling will be cheaper in terms of weight

2023-02-24 19:38 UTC, mrq1911 commented on otc/src/lib.rs
> +        pub fn fill_order(
also, it could only have one simple param, opposed to 2 with partial fill

2023-02-24 19:38 UTC, mrq1911 commented on otc/src/lib.rs
> +                let amount_out = Self::fetch_amount_out(order_id, order);
you don't have to fetch this in this case, `unreserve_named` with `Balance::MAX` will unreserve everything reserved. function actually returns what was unserved so you get that value anyway and can use it in `OrderCanceled` event - which would be very interesting information for partially fillable orders

2023-02-24 19:38 UTC, mrq1911 commented on otc/src/lib.rs
> +        /// - `amount`: Amount which is being filled
```suggestion
```

2023-02-24 19:38 UTC, mrq1911 commented on otc/src/types.rs
> +pub type OrderId = u32;
i guess that is a disadvantage of using named reserves for accounting to have only 2^32 them :)

2023-02-24 19:38 UTC, mrq1911 commented on otc/src/lib.rs
> +            amount: Balance,
amount_in

2023-02-24 19:38 UTC, mrq1911 commented on otc/src/lib.rs
> +            amount_receive: Balance,
amount_out

2023-02-24 19:38 UTC, mrq1911 commented on otc/src/lib.rs
> +            amount: Balance,
amount_in, amount_out should be added for consistency as well

2023-02-24 19:38 UTC, mrq1911 commented on otc/src/lib.rs
> +    fn calculate_amount_receive(
calculate_filled_amount_out

2023-02-24 19:38 UTC, mrq1911 commented on otc/src/lib.rs
> +        ensure!(order.amount_in >= amount, Error::<T>::CannotFillMoreThanOrdered);
i would allow this to make sure if somebody fills a portion before you when you want to fully fill, you get at least something with your fill instead of failed tx and delayed full fill for maker, so you would fill the order not with exact amount_in but `up to` amount_in

2023-02-24 19:42 UTC, mrq1911 commented on otc/src/lib.rs
> +    pub enum Event<T: Config> {
prefix Order on all events is potentially redundant

2023-02-27 18:16 UTC, vgantchev commented on otc/src/lib.rs
> +        ensure!(order.amount_in >= amount, Error::<T>::CannotFillMoreThanOrdered);
hmm not sure - this adds quite some complexity (from code, testing but also UX pov), while the benefits of addressing this edge case are questionable

I would revisit it in a future iteration if that's ok with you?

2023-02-27 18:21 UTC, jak-pan commented on otc/src/lib.rs
> +        ensure!(order.amount_in >= amount, Error::<T>::CannotFillMoreThanOrdered);
Would maybe create separate callable function for this? (partial fill)

2023-02-27 18:22 UTC, vgantchev commented on otc/src/lib.rs
> +
that's everywhere in warehouse, uses tabs for identation :-(

2023-02-27 18:33 UTC, vgantchev commented on otc/src/lib.rs
> +        pub fn fill_order(
The weight should not be very different - in the one case you mutate a value, in the other you mutate the whole record to None

I am not a big fan of splitting it because partial_fill would still need to be able to handle full fill, can't trust frontend that it will call correct function also it can be exploited

2023-02-27 19:03 UTC, vgantchev commented on otc/src/lib.rs
> +        ensure!(order.amount_in >= amount, Error::<T>::CannotFillMoreThanOrdered);
@jak-pan even if we have a separate extrinsic for partial_fill, it still needs to be able to handle a complete fill imo

Otherwise attackers can dispatch a complete fill via partial_fill, which will lead to unfreeze of the balance which is used as storage bond, without cleaning the record :(

2023-02-27 19:08 UTC, vgantchev commented on otc/src/lib.rs
> +        ensure!(order.amount_in >= amount, Error::<T>::CannotFillMoreThanOrdered);
or we can add an extra validation to partial_fill that it must leave at least 5xED, if you think that splitting in 2 is rly worth it

2023-02-28 11:15 UTC, mrq1911 commented on otc/src/lib.rs
> +
i was reffering to the vertical spacing - e.g. extra lines inserted into code

2023-02-28 11:17 UTC, mrq1911 commented on otc/src/lib.rs
> +                let amount_out = Self::fetch_amount_out(order_id, order);
i thought it returns only what it really unreserved, nevermind then

2023-02-28 12:37 UTC, mrq1911 commented on otc/src/tests/mock.rs
> +pub fn named_reserve_identifier(order_id: OrderId) -> [u8; 8] {
i would use the same implementation as is in the pallet, no need to copypsate. also i would note that this yield unreadable strings for UI
```
String.fromCharCode(...[111, 116, 99, 0, 0, 0, 1, 0])
'otc\x00\x00\x00\x01\x00'
```

2023-02-28 12:57 UTC, mrq1911 commented on otc/src/tests/mock.rs
> +pub fn named_reserve_identifier(order_id: OrderId) -> [u8; 8] {
also currently runtime lets you have only 50 reserves per account, so with this it could be pretty easy to exceed this limit. i am leaning towards not abusing this identification for accounting and do the internal accounting in pallet instead, as it will solve 3 issues:
- increase number of global orders to u128::MAX from u32::MAX
- unreadable reserve id
- reserve id generation on ui
- limited orders per account to 50

2023-02-28 17:06 UTC, vgantchev commented on otc/src/tests/mock.rs
> +pub fn named_reserve_identifier(order_id: OrderId) -> [u8; 8] {
Here storage is very cheap and non-problematic, a good reason to no waste named reserves on this

DCA is up to your consideration, i already left a comment on the PR

2023-02-28 17:49 UTC, vgantchev commented on otc/src/lib.rs
> +
i usually try to logically separate code with empty lines for better readability, but in the case that you commented it was excessive indeed :)

2023-03-01 11:26 UTC, mrq1911 commented on otc/src/lib.rs
> +                T::Currency::unreserve(order.asset_out, &order.owner, order.amount_out);
i would still used named reserve, but with just constant identifier to separate what user is reserving in the otc vs dca, etc

2023-03-01 12:18 UTC, vgantchev commented on otc/src/lib.rs
> +                T::Currency::unreserve(order.asset_out, &order.owner, order.amount_out);
ok i will change back to named with const but this was not very explicit in your previous comments :)

2023-03-10 16:33 UTC, enthusiastmartin commented on otc/src/tests/invariants.rs
> +            amount_in in Just(amount_in),
it is not possible to have amount out < amount in at all ? 

if that;'s the case, then it is ok. otherwise, you'd want to have such scenarios covered too.

2023-03-10 16:33 UTC, enthusiastmartin commented on otc/src/tests/invariants.rs
> +            let initial_price = initial_amount_out / initial_amount_in;
i'd use some fixed type here.

2023-03-13 13:22 UTC, mrq1911 requested changes

2023-03-13 16:24 UTC, vgantchev commented on otc/src/lib.rs
> +        AssetNotRegistered,
@mrq1911 this is only true for asset_out which is reserved - otherwise nothing prevents you from creating an order for a non-existent asset_in, with all issues down the stream (UI).

Please LMK if I should still remove

2023-03-14 12:30 UTC, dmoka commented on otc/src/benchmarks.rs
> +fn prepare<T: Config>() -> Result<(u32, u32), DispatchError>
I would name it as "create_assets_in_registry"

2023-03-14 12:30 UTC, dmoka commented on otc/src/lib.rs
> +            // Validations
instead of having a comment, I would just wrap all the 4 validations to a method "validate_new_order" method, with 2 arguments: order and amount_out

2023-03-14 12:30 UTC, dmoka commented on otc/src/lib.rs
> +            let order_id = <NextOrderId<T>>::try_mutate(|next_id| -> result::Result<OrderId, DispatchError> {
the way it is implemented is on a different abstraction level than what it functionally does.

I would extract it to a method called "get_next_order_id".

2023-03-14 12:30 UTC, dmoka commented on otc/src/lib.rs
> +                let id = *next_id;
Do we start at id 0? Should not we start at id 1?

2023-03-14 12:30 UTC, dmoka commented on otc/src/lib.rs
> +        /// - `order_id`: ID of the order
I guess you miss the origin in the API doc.

2023-03-14 12:30 UTC, dmoka commented on otc/src/lib.rs
> +        /// - `order_id`: ID of the order
It is also true for other extrinsics

2023-03-14 12:30 UTC, dmoka commented on otc/src/lib.rs
> +        #[transactional]
AFAIK, this transactional annotation is not needed anymore. 

also true for other extrinsics

2023-03-14 12:30 UTC, dmoka commented on otc/src/lib.rs
> +        /// - `partially_fillable`: Flag indicating whether users can fill the order partially
As far as I see in other pallets, we usually also document that emitted events like

```
		/// Emits `<EventName>` event when <status>.
```

If you do, please do it in other extrinsics as well.

2023-03-14 12:30 UTC, dmoka commented on otc/src/lib.rs
> +        amount_initial.checked_sub(amount_change).ok_or(Error::<T>::MathError)
Maybe `ArithmeticError::Underflow` would be better? If so, you could use Underflow/Overflow in other places too, so we can get rid of this customer math error.

2023-03-14 12:30 UTC, dmoka commented on otc/src/lib.rs
> +    fn execute_deal(
`execute_order` ?

2023-03-14 12:30 UTC, dmoka commented on otc/src/tests/place_order.rs
> +}
Awesome and clean tests! Also went through the code with mutation testing, and all mutations are killed! Great job!

2023-03-16 16:23 UTC, mrq1911 commented on otc/src/lib.rs
> +        AssetNotRegistered,
we can keep it then

2023-03-16 17:45 UTC, mrq1911 commented on otc/src/lib.rs
> +            <Orders<T>>::remove(order_id);
i am not sure that this actually removes the key from storage as well, not according to @nohaapav

2023-03-17 14:25 UTC, vgantchev commented on otc/src/lib.rs
> +            // Validations
it was in a separate method and was moved to in-function per @mrq1911 request

2023-03-17 14:41 UTC, vgantchev commented on otc/src/lib.rs
> +            <Orders<T>>::remove(order_id);
as discussed during call - not possible, probably bc remapping brings O(n)

2023-03-17 15:26 UTC, vgantchev commented on otc/src/lib.rs
> +        /// - `order_id`: ID of the order
yup, and we also haven't documented origin in other features (consistency)

2023-03-18 21:06 UTC, mrq1911 approved these changes

2023-03-18 21:15 UTC, merged