feat: dca
galacticcouncil/warehouse pull request #169
Opened 2023-02-21 12:23 UTC by dmoka

Extracting some helper and common logic to this repo, for the DCA functionality

2023-02-24 09:17 UTC, enthusiastmartin commented on traits/src/pools.rs
> +pub trait PriceProvider<AssetId> {
why we need two different traits for price provider which it seems would do exactly the same ?

2023-02-24 09:17 UTC, enthusiastmartin commented on relaychain-info/src/lib.rs
> +    pub(super) type ParentHash<T> = StorageValue<_, Hash, ValueQuery>;
could you add some description behind the motivation to store this value ?

2023-02-28 13:16 UTC, vgantchev commented
should we have whole dca pallet in warehouse? allowing to eventually reuse for Snek?

2023-05-26 13:26 UTC, mrq1911 requested changes

2023-05-26 13:26 UTC, mrq1911 commented on route-executor/src/lib.rs
> +impl<T: Config> TradeAmountsCalculator<T::AssetId, T::Balance> for Pallet<T> {
is this still used with the new version with router?

2023-05-26 13:26 UTC, mrq1911 commented on traits/src/pools.rs
> +pub trait PriceProvider<AssetId> {
@dmoka ?

2023-05-29 07:53 UTC, dmoka commented
> should we have whole dca pallet in warehouse? allowing to eventually reuse for Snek?

as we will have the mono repo soon, this is not necessary anymore

2023-05-29 07:55 UTC, dmoka commented on route-executor/src/lib.rs
> +impl<T: Config> TradeAmountsCalculator<T::AssetId, T::Balance> for Pallet<T> {
yes, it was added lately, because we need to determine the exact amount_in for buy orders.

Instead of duplicating the logic in hydra, I just exposed this function by using the trait.

2023-05-29 13:15 UTC, mrq1911 commented
move it to the hydradx dca PR when we have monorepo

2023-05-29 13:15 UTC, closed without merging