Feat/collator rewards
galacticcouncil/warehouse pull request #43
Opened 2022-04-11 12:16 UTC by martinfridrich

Pallet for collator reward at the beginning of each session.

https://github.com/galacticcouncil/HydraDX-node/issues/389

2022-04-11 19:35 UTC, lumir-mrkva requested changes
is there any pr on hydradx to integrate this already?

2022-04-11 19:35 UTC, lumir-mrkva commented on collator-rewards/src/lib.rs
> +        type NotRewardedCollators: Get<Vec<Self::AccountId>>;
ExcludedCollators

2022-04-11 19:35 UTC, lumir-mrkva commented on collator-rewards/src/lib.rs
> +use frame_support::traits::OneSessionHandler;
uses just on top of namespace pls

2022-04-11 19:35 UTC, lumir-mrkva commented on collator-rewards/src/lib.rs
> +                    continue;
`if ok then event else warn` would be cleaner

2022-04-11 19:35 UTC, lumir-mrkva commented on collator-rewards/src/lib.rs
> +        /// Coallator was rewarded.
typo
```suggestion
        /// Collator was rewarded.
```

2022-04-11 19:35 UTC, lumir-mrkva commented on collator-rewards/src/lib.rs
> +            reward_currency: T::CurrencyId,
currency

2022-04-11 19:35 UTC, lumir-mrkva commented on collator-rewards/src/tests.rs
> +        //this are blaklisted collators and should not be rewarded
```suggestion
        // excluded collators and should not be rewarded
```

2022-04-11 19:35 UTC, lumir-mrkva commented on collator-rewards/src/tests.rs
> +        //this collators which should be rewarded
```suggestion
        // these collators should be rewarded
```

2022-04-11 19:35 UTC, lumir-mrkva commented on collator-rewards/src/tests.rs
> +        //this are blaklisted collators and should not be rewarded
checks for 0 balances are redundant and should be removed to reduce clutter, if this is not true, it will fail in later assert as well

2022-04-11 19:35 UTC, lumir-mrkva commented on collator-rewards/src/tests.rs
> +        let collator_set = vec![
you're not actually testing the excluded collators as there is no one from them is the set

2022-04-15 08:05 UTC, enthusiastmartin commented on collator-rewards/src/lib.rs
> +                let result = T::Currency::deposit(T::RewardCurrencyId::get(), collator, T::RewardPerCollator::get());
Is this intended behavior ?  

i mean, minting rewards in any currency ?

2022-04-15 09:35 UTC, martinfridrich commented on collator-rewards/src/lib.rs
> +                let result = T::Currency::deposit(T::RewardCurrencyId::get(), collator, T::RewardPerCollator::get());
Yes, minting is intended. "any currency" it wasn't requirement I've just made it configurable.

2022-05-06 08:27 UTC, lumir-mrkva approved these changes

2022-05-06 08:27 UTC, merged