Add types to set tx fee asset on new account
galacticcouncil/warehouse pull request #54
Opened 2022-06-06 08:57 UTC by apopiak

2022-06-06 09:00 UTC, jak-pan commented on transaction-multi-payment/src/lib.rs
> +/// Note: The fee currency is only removed if the system account is gone.
Is this a technical limitation or logical decision? I would tend to think that we might also do this when your balance for the asset that was set was reaped. Just a thought.

2022-06-06 09:03 UTC, enthusiastmartin commented on Cargo.toml
> +orml-utilities = { git = "https://github.com/apopiak/open-runtime-module-library", branch = "apopiak/on-new-account-9-17" }
why need of all these crates ?

2022-06-06 09:03 UTC, enthusiastmartin commented on transaction-multi-payment/src/lib.rs
> +        }
i wonder if you could just call remove without the check. 

can there be a case where you would like to keep it in the currency map if it does not exist ?

2022-06-06 09:04 UTC, enthusiastmartin commented on transaction-multi-payment/src/lib.rs
> +        }
ah..i think i misread the condition

2022-06-06 09:10 UTC, apopiak commented on transaction-multi-payment/src/lib.rs
> +/// Note: The fee currency is only removed if the system account is gone.
Ah, interesting idea!

2022-06-06 09:13 UTC, enthusiastmartin commented on transaction-multi-payment/src/lib.rs
> +        }
is the "happened" called only when orml-tokens removes account from its storage? 

i guess so, so in that case - ignore this comment.

2022-06-06 09:13 UTC, apopiak commented on Cargo.toml
> +orml-utilities = { git = "https://github.com/apopiak/open-runtime-module-library", branch = "apopiak/on-new-account-9-17" }
Because I'm using https://github.com/open-web3-stack/open-runtime-module-library/pull/754 , it's not merged and I just replaced all of the orml crates used. Happy to reduce the list if we don't need some of them.

2022-06-06 09:15 UTC, apopiak commented on transaction-multi-payment/src/lib.rs
> +        }
We should not just remove because this is called for *every currency account removed*.
So if you have BSX, KSM and aUSD in your account and transfer out all the aUSD, this callback will be called, but would not lead us to want to remove the tx fee currency (especially not if it's set to KSM).

2022-06-06 09:58 UTC, apopiak commented on transaction-multi-payment/src/lib.rs
> +/// Note: The fee currency is only removed if the system account is gone.
Ok, implemented. Note, though, that this incurs more storage reads on deletion.

2022-06-13 09:48 UTC, enthusiastmartin requested changes
looks good to me.

2022-06-13 09:49 UTC, enthusiastmartin approved these changes

2022-06-13 10:47 UTC, jak-pan approved these changes
LGTM

2022-06-13 19:53 UTC, merged