chore: polkadot 0.9.26
galacticcouncil/warehouse pull request #70
Opened 2022-07-19 19:08 UTC by Roznovjak

2022-08-08 19:58 UTC, lumir-mrkva commented
Task linked: [CU-2p79uye Upgrade to polkadot-v0.9.26](https://app.clickup.com/t/2p79uye)

2022-08-09 21:19 UTC, lumir-mrkva requested changes

2022-08-09 21:19 UTC, lumir-mrkva commented on nft/src/lib.rs
> +    fn owned_in_collection(class: &Self::CollectionId, who: &T::AccountId) -> Box<dyn Iterator<Item = Self::ItemId>> {
inconsistent renaming

cc @green-jay what should we do with this unique class -> collection mess?
how does it affect kodadot?

2022-08-09 21:19 UTC, lumir-mrkva commented on nft/Cargo.toml
> +version = "3.3.1"
as it stands now, this is a huge breaking change ... should be bump to 4.0.0

2022-09-16 12:35 UTC, lumir-mrkva approved these changes

2022-09-16 13:43 UTC, Roznovjak commented on nft/src/lib.rs
> +    fn owned_in_collection(class: &Self::CollectionId, who: &T::AccountId) -> Box<dyn Iterator<Item = Self::ItemId>> {
We decided to rename everything to `Collection` and `Item`.

2022-09-29 14:31 UTC, Roznovjak commented
Closing in favor of #83

2022-09-29 14:31 UTC, closed without merging