[WIP] Next Generation Oracle
galacticcouncil/warehouse pull request #76
Opened 2022-08-05 15:32 UTC by apopiak

... using exponential moving averages (EMA).
See [EMA article](https://nestedsoftware.com/2018/04/04/exponential-moving-average-on-streaming-data-4hhl.24876.html) and [EMA Wikipedia section](https://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average).

2022-08-08 06:41 UTC, dmoka commented on price-oracle/src/lib.rs
> +    #[pallet::getter(fn oracle)]
maybe we can call this getter as `oracles` to follow the convention 
```suggestion
    #[pallet::getter(fn oracles)]
```

2022-08-08 06:41 UTC, dmoka commented on price-oracle/src/lib.rs
> +            Oracles::<T>::mutate(pair_id.clone(), 1, |oracle| {
If possible, I would extract line 291-296, as the same logic is used 3 times in a row.

2022-08-08 06:41 UTC, dmoka commented on price-oracle/src/lib.rs
> +        StorageDoubleMap<_, Twox64Concat, AssetPairId, Twox64Concat, u32, PriceEntry, OptionQuery>;
I feel that by defining an alias for `key2` of type `u32`, we could make this storage more descriptive.

2022-08-08 06:41 UTC, dmoka commented on price-oracle/src/types.rs
> +        // TODO: include time
todo :)

2022-08-08 09:28 UTC, apopiak commented on price-oracle/src/lib.rs
> +    #[pallet::getter(fn oracle)]
The convention should be singular for maps (at least where it makes sense, might be different if you store a vec of things in a map entry) and has been at Parity IIRC. Using the getter I get one oracle entry, not several.

2022-08-08 10:25 UTC, lumir-mrkva commented
Task linked: [CU-2v0w820 next gen oracle](https://app.clickup.com/t/2v0w820)

2022-08-08 10:25 UTC, dmoka commented on price-oracle/src/lib.rs
> +    #[pallet::getter(fn oracle)]
ah okay, I agree with you. I am working on a pallet right now (nft marketplace) and over there we have plural namings for both maps and getters, despite the fact that we store singular objects and not `vec` or so. But then I might need to do some refactorings on my pallet myself x)

2022-08-26 12:59 UTC, Roznovjak reviewed
I would move `AssetPairId` type to types.rs . This type can also be changed to `BoundedVec<u8, 11>`. It might come handy later if we want to use bounded types for all the storage entries.

2022-08-30 09:25 UTC, apopiak commented
> I would move `AssetPairId` type to types.rs . This type can also be changed to `BoundedVec<u8, 11>`. It might come handy later if we want to use bounded types for all the storage entries.

I'm thinking about extracting it into an associated type, actually, and thus pulling it into the traits crate.

2022-10-10 11:48 UTC, apopiak reviewed
Would be good to get your opinion on how to associate smoothing factors with oracle type.

2022-10-10 11:48 UTC, apopiak commented on ema-oracle/src/lib.rs
> +}
@poliwop Has suggested associating the smoothing factor directly with the oracle, skipping the path via block period.

2022-10-10 11:48 UTC, apopiak commented on ema-oracle/src/lib.rs
> +            NMapKey<Twox64Concat, T::BlockNumber>,
If we drop the period I would replace this key with the Oracle identifier (I'm worried using FixedU128 as a key would get too messy.)
Another option if we don't want to change the set of oracles would be to collapse the different Oracles into one storage key:
```Rust
StorageDoubleMap<Twox64Concat, Source, Twox64Concat, (AssetId, AssetId), [(OracleEntry<T::BlockNumber>, T::BlockNumber); 4]>
```
Or similar

2022-10-14 14:41 UTC, poliwop commented on ema-oracle/src/lib.rs
> +            NMapKey<Twox64Concat, T::BlockNumber>,
not sure I fully understand the issue with using FixedU128 as a key... but if alpha (smoothing factor) is in (0,1], you could compute K=1/alpha as a u128 and use that as the key. I believe different alphas which have matching K would be so close we would likely not want to allow two different oracles with such close parameters anyway (assuming the division is done carefully to minimize rounding error).

For the purposes of the actual computation, I would still store the smoothing factor directly, but another option would be to just store K and recompute smoothing factor from it. However I wouldn't really see the advantage of that over the current implementation.

2022-10-18 08:22 UTC, dmoka commented on traits/src/oracle.rs
> +    pub a_in: Balance,
if possible, I would use more intention-revealing names here

2022-10-18 08:22 UTC, dmoka commented on traits/src/oracle.rs
> +    pub b_in: Balance,
what is the reason having the fields in this order, namely ain-bout-aout-bin. Why not for example ain-aout-bin-bout?

2022-10-18 08:22 UTC, dmoka commented on traits/src/oracle.rs
> +    pub fn saturating_add(&self, rhs: &Self) -> Self {
what does `rhs` mean? If it is a custom or less-known abbreviation, I would write it out.

2022-10-18 08:22 UTC, dmoka commented on traits/src/oracle.rs
> +impl<AssetId, BlockNumber, Price> AggregatedPriceOracle<AssetId, BlockNumber, Price> for AlwaysPriceOfOne
If this is only used in tests, then I would place it next to the tests.

2022-10-20 09:41 UTC, apopiak commented on ema-oracle/src/tests/invariants.rs
> +    #[test]
the default is 256
I chose the config (or lack of config) to make sure the tests run quickly

2022-10-20 09:41 UTC, apopiak commented on traits/src/oracle.rs
> +    pub b_in: Balance,
a_in and b_out mostly go together (you swap token a in and token b out), same for a_out and b_in

2022-10-20 09:42 UTC, apopiak commented on traits/src/oracle.rs
> +    pub fn saturating_add(&self, rhs: &Self) -> Self {
it stands for right-hand-side and is a common abbreviation in math code

2022-10-20 09:43 UTC, apopiak commented on traits/src/oracle.rs
> +    pub fn saturating_add(&self, rhs: &Self) -> Self {
I don't really care what it's called. We can change to `other`, too :shrug:

2022-10-20 18:26 UTC, dmoka commented on traits/src/oracle.rs
> +    pub fn saturating_add(&self, rhs: &Self) -> Self {
ah I see it now. Just checked and there is also `rhs` used in other standard rust packages, f.e.: [u32](https://doc.rust-lang.org/std/primitive.u32.html#method.checked_add) 

Leave it then to follow the convention, and personally I learned something new, thanks for the info!

2022-10-20 18:29 UTC, dmoka commented on traits/src/oracle.rs
> +    pub b_in: Balance,
ah okay, the ordering make sense then.

Just for my understanding: so a_in+b_out together represents a sell swap, and a_out+b_in represents a buy swap?

2022-10-28 23:11 UTC, lumir-mrkva requested changes
pls merge master properly so the PR is not polluted with 0.9.28 related changes

2023-01-13 16:09 UTC, apopiak commented on traits/src/oracle.rs
> +    pub b_in: Balance,
I don't think that's the right way to think about it? IIUC it doesn't matter for the oracle whether it was a buy or a sell, just whether token a moved into or out of the pool (and correspondingly for b).

2023-01-17 17:31 UTC, apopiak commented on traits/src/oracle.rs
> +    pub a_in: Balance,
What direction are you thinking here?

2023-01-17 17:32 UTC, apopiak commented on traits/src/oracle.rs
> +impl<AssetId, BlockNumber, Price> AggregatedPriceOracle<AssetId, BlockNumber, Price> for AlwaysPriceOfOne
Do you mean in a test-util crate? Because this is meant for tests generally (e.g. also pallets that want to use the trait)

2023-01-18 08:29 UTC, enthusiastmartin approved these changes

2023-01-18 08:29 UTC, enthusiastmartin commented on ema-oracle/src/lib.rs
> +        type MaxTradesPerBlock: Get<u32>;
i'd suggest to assert this is set to > 0 in integrity_test hook. The reason is that it is used in division later on ( not safe division ). Just to be sure.

2023-01-18 08:29 UTC, enthusiastmartin commented on ema-oracle/src/lib.rs
> +            // TODO: Can we also divide the proof size weight the same way?
TODO?

2023-01-18 08:29 UTC, enthusiastmartin commented on ema-oracle/src/lib.rs
> +            // TODO: Can we also divide the proof size weight the same way?
TODO

2023-01-18 08:29 UTC, enthusiastmartin commented on ema-oracle/src/types.rs
> +    pub fn inverted(&self) -> Self {
not that important, although I'd think that you use the inverted entry and there would not be a need to keep the previous one and therefore you could consider:

```suggestion
    pub fn inverted(self) -> Self {
```

2023-01-20 12:06 UTC, apopiak commented on ema-oracle/src/lib.rs
> +            // TODO: Can we also divide the proof size weight the same way?
I would create an issue, seems not worth addressing on the first pass, what do you think?

2023-01-20 12:22 UTC, apopiak commented on ema-oracle/src/types.rs
> +        };
@enthusiastmartin I'm actually not 100% sure what the semantics of an inverted price should be. I could also see someone arguing for max value or for the operation to fail. What do you think?

2023-01-30 14:31 UTC, apopiak commented on ema-oracle/src/lib.rs
> +                accumulator.try_insert((src, assets), oracle_entry).unwrap_or_else(|((src, assets), entry)| {
this should fail the trade -> change callback to result type

2023-01-30 14:57 UTC, apopiak commented on ema-oracle/src/lib.rs
> +                true
return weight here

2023-01-30 15:05 UTC, apopiak commented on ema-oracle/src/lib.rs
> +            // TODO: Can we also divide the proof size weight the same way?
We should be able to divide proof size the same way as computational weight

2023-01-31 14:24 UTC, jak-pan commented on traits/src/lib.rs
> +        liq_amount: Balance,
This will need to change to absolute amounts in the pool and as such it's probably mergable with the other handler but I'm not sure which one should we keep

2023-01-31 14:25 UTC, jak-pan commented on traits/src/lib.rs
> +        liq_amount: Balance,
We could call this on_before_trade or on_after_trade and sync up with volume limits

2023-01-31 14:27 UTC, jak-pan commented on traits/src/lib.rs
> +        liq_amount: Balance,
cc https://github.com/galacticcouncil/warehouse/pull/133/files#r1092011502

2023-01-31 14:54 UTC, jak-pan commented on ema-oracle/src/lib.rs
> +        // We assume that zero values are not valid and can be ignored.
This could happen when the pool is destroyed

2023-01-31 14:57 UTC, jak-pan commented on ema-oracle/src/lib.rs
> +pub fn determine_normalized_price(
This probably won't be the same for stableswap and omnipool. Do we need to make this more generic?

2023-01-31 15:52 UTC, apopiak commented on ema-oracle/src/lib.rs
> +pub fn determine_normalized_price(
This seems very unlikely to change. Happy to make it generic as soon as it needs to be.

2023-01-31 15:58 UTC, apopiak commented on ema-oracle/src/types.rs
> +        };
Ok, with the incoming amounts `on_liquidity_changed` being possibly zero (see https://github.com/galacticcouncil/warehouse/pull/76#discussion_r1092050361) the semantics should probably be that zero inverts to zero

2023-02-27 13:36 UTC, merged