feat: Stableswap v2
galacticcouncil/warehouse pull request #82
Opened 2022-09-19 07:45 UTC by enthusiastmartin

2022-09-26 11:58 UTC, martinfridrich reviewed
I see potential way to merge iterations in `add_liquidity` into 1 `iter` but it would complicate inner code and also do more work before it fails so I'm not sure if it's worthed. Especially if set is that small. 
Also I see way how to get rid of `Btree`s. In my experience(from other lang) simple `find` is usually faster for small sets than construct more complicated data structure, but I didn't benchmarked it in rust.
If we are interested in this I can try to draft it.

2022-09-26 11:58 UTC, martinfridrich commented on stableswap/src/lib.rs
> +            pool_assets.sort();
I would suggest adding failing test with unsorted assets so this line is not removed by accident.

2022-09-29 08:55 UTC, enthusiastmartin commented
> I see potential way to merge iterations in `add_liquidity` into 1 `iter` but it would complicate inner code and also do more work before it fails so I'm not sure if it's worthed. Especially if set is that small. Also I see way how to get rid of `Btree`s. In my experience(from other lang) simple `find` is usually faster for small sets than construct more complicated data structure, but I didn't benchmarked it in rust. If we are interested in this I can try to draft it.

i agree that it could be in one, however, this would make it quite complicated. 

because the thing is that add_liquidity can take any number of assets.  eg. if you have a pool with 5 assets, you can just add liquidity of one asset.
however you still need to load all asset's reserves and you also need to verify that all provided assets are in the pool. 

in this way, if there is an asset which does not belong to the pool - we might read balances of other assets only to find out that the input is incorrect.  

both approach have good and bad points.

2022-09-29 08:58 UTC, enthusiastmartin commented on stableswap/src/lib.rs
> +            pool_assets.sort();
This could be already checked by existing tests because it wont fail with unsorted assets.  the result might e different. so i believe existing tests would already fail, if it is not sorted. i will test.

2022-09-29 09:29 UTC, martinfridrich commented on stableswap/src/lib.rs
> +            pool_assets.sort();
All the tests are passing if I comments this line. Tests are using sorted vec as input

2022-10-06 09:39 UTC, dmoka commented on stableswap/src/impls.rs
> +use crate::{Balance, Config, Pallet, Zero};
I would call this file `trade_execution.rs` to make it more descriptive.

We also use he same naming in LBP and XYK

2022-10-06 09:39 UTC, dmoka commented on stableswap/src/impls.rs
> +impl<T: Config> TradeExecution<T::Origin, T::AccountId, T::AssetId, Balance> for Pallet<T> {
Since we add router support, we would also need to add support to Basilisk, right? I mean in the basilisk runtime route-executor config, amm pools associated type.

2022-10-06 09:39 UTC, dmoka commented on stableswap/src/lib.rs
> +        SellExecuted {
As `SellExecuted` and `BuyExecuted` has the exact same properties, shall we use just one `TradeExecuted` for both?

2022-10-21 08:41 UTC, enthusiastmartin commented on stableswap/src/lib.rs
> +                pool.assets.clone().into(), //TODO: fix the trait to accept refeerence instead
removed todo.

should be refactor as part of https://github.com/galacticcouncil/warehouse/issues/52

2022-10-21 08:46 UTC, enthusiastmartin commented on stableswap/src/impls.rs
> +impl<T: Config> TradeExecution<T::Origin, T::AccountId, T::AssetId, Balance> for Pallet<T> {
I dont get what you mean. can you elaborate?

2022-10-21 08:47 UTC, enthusiastmartin commented on stableswap/src/lib.rs
> +        SellExecuted {
I'd keep it consistent with other pools where we have both sell/buy executed events.

2022-10-24 08:00 UTC, dmoka commented on stableswap/src/impls.rs
> +impl<T: Config> TradeExecution<T::Origin, T::AccountId, T::AssetId, Balance> for Pallet<T> {
what I mean is that right now we are in the warehouse project. In order to add the stableswap v2 to Basilisk or Hydra, we would need to extend the `pallet_route_executor` config in the given project.

So we would need to add Stableswap in `type AMM`. Or not?

![image](https://user-images.githubusercontent.com/9437108/197476574-69e2446d-6cad-4c54-861f-3ad96e449eb3.png)

2022-10-24 08:56 UTC, enthusiastmartin commented on stableswap/src/impls.rs
> +impl<T: Config> TradeExecution<T::Origin, T::AccountId, T::AssetId, Balance> for Pallet<T> {
ah yes. when stableswap is added to basilisk, and support for the router is needed - then yes.

2022-10-28 23:10 UTC, lumir-mrkva requested changes

2022-10-28 23:10 UTC, lumir-mrkva commented on stableswap/Cargo.toml
> +description = '2 asset stabelswap/curve AMM'
```suggestion
description = 'AMM for correlated assets'
```

2022-10-28 23:10 UTC, lumir-mrkva commented on stableswap/src/lib.rs
> +        type CreatePoolOrigin: EnsureOrigin<Self::Origin>;
this origin can also modify the existing pool. the more accurate name is required, for example: `PoolMasterOrigin`

2022-11-02 13:17 UTC, dmoka approved these changes
LGTM.

Once stableswap is added to Basilisk, we could extend our router integration tests in Basilisk-node. It would be nice to have integration tests having 3 different kind of pools, so LBP, XYK and stableswap.

2022-11-11 16:41 UTC, lumir-mrkva approved these changes

2022-12-07 14:33 UTC, merged